language: go

go:
  - 1.7
  - tip

script:
  - diff -u <(echo -n) <(gofmt -s -d .)
  - go tool vet .
  - golint
  - go build

before_script:
  - go get -u github.com/gorilla/mux
  - go get -u gopkg.in/h2non/bimg.v1
  - go get -u github.com/golang/lint/golint
